//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 17/09/2024 12:30:31
namespace Ms_configuration.Models
{
    /// <summary>
    /// There are no comments for RabbitMqConfigModelSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("RabbitMqConfigModelSingle")]
    public partial class RabbitMqConfigModelSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<RabbitMqConfigModel>
    {
        /// <summary>
        /// Initialize a new RabbitMqConfigModelSingle object.
        /// </summary>
        public RabbitMqConfigModelSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new RabbitMqConfigModelSingle object.
        /// </summary>
        public RabbitMqConfigModelSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new RabbitMqConfigModelSingle object.
        /// </summary>
        public RabbitMqConfigModelSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<RabbitMqConfigModel> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for RabbitMqConfigModel in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("RabbitMqConfigModel")]
    public partial class RabbitMqConfigModel : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new RabbitMqConfigModel object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="hostname">Initial value of Hostname.</param>
        /// <param name="port">Initial value of Port.</param>
        /// <param name="username">Initial value of Username.</param>
        /// <param name="password">Initial value of Password.</param>
        /// <param name="creationDate">Initial value of CreationDate.</param>
        /// <param name="deleted">Initial value of Deleted.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static RabbitMqConfigModel CreateRabbitMqConfigModel(global::System.Guid ID, 
                    string hostname, 
                    int port, 
                    string username, 
                    string password, 
                    global::System.DateTimeOffset creationDate, 
                    bool deleted)
        {
            RabbitMqConfigModel rabbitMqConfigModel = new RabbitMqConfigModel();
            rabbitMqConfigModel.Id = ID;
            rabbitMqConfigModel.Hostname = hostname;
            rabbitMqConfigModel.Port = port;
            rabbitMqConfigModel.Username = username;
            rabbitMqConfigModel.Password = password;
            rabbitMqConfigModel.CreationDate = creationDate;
            rabbitMqConfigModel.Deleted = deleted;
            return rabbitMqConfigModel;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Id")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "Id is required.")]
        public virtual global::System.Guid Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Hostname in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Hostname")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "Hostname is required.")]
        public virtual string Hostname
        {
            get
            {
                return this._Hostname;
            }
            set
            {
                this.OnHostnameChanging(value);
                this._Hostname = value;
                this.OnHostnameChanged();
                this.OnPropertyChanged("Hostname");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Hostname;
        partial void OnHostnameChanging(string value);
        partial void OnHostnameChanged();
        /// <summary>
        /// There are no comments for Property Port in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Port")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "Port is required.")]
        public virtual int Port
        {
            get
            {
                return this._Port;
            }
            set
            {
                this.OnPortChanging(value);
                this._Port = value;
                this.OnPortChanged();
                this.OnPropertyChanged("Port");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private int _Port;
        partial void OnPortChanging(int value);
        partial void OnPortChanged();
        /// <summary>
        /// There are no comments for Property Username in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Username")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "Username is required.")]
        public virtual string Username
        {
            get
            {
                return this._Username;
            }
            set
            {
                this.OnUsernameChanging(value);
                this._Username = value;
                this.OnUsernameChanged();
                this.OnPropertyChanged("Username");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Username;
        partial void OnUsernameChanging(string value);
        partial void OnUsernameChanged();
        /// <summary>
        /// There are no comments for Property Password in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Password")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "Password is required.")]
        public virtual string Password
        {
            get
            {
                return this._Password;
            }
            set
            {
                this.OnPasswordChanging(value);
                this._Password = value;
                this.OnPasswordChanged();
                this.OnPropertyChanged("Password");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Password;
        partial void OnPasswordChanging(string value);
        partial void OnPasswordChanged();
        /// <summary>
        /// There are no comments for Property CreationDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("CreationDate")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "CreationDate is required.")]
        public virtual global::System.DateTimeOffset CreationDate
        {
            get
            {
                return this._CreationDate;
            }
            set
            {
                this.OnCreationDateChanging(value);
                this._CreationDate = value;
                this.OnCreationDateChanged();
                this.OnPropertyChanged("CreationDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.DateTimeOffset _CreationDate;
        partial void OnCreationDateChanging(global::System.DateTimeOffset value);
        partial void OnCreationDateChanged();
        /// <summary>
        /// There are no comments for Property Deleted in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Deleted")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "Deleted is required.")]
        public virtual bool Deleted
        {
            get
            {
                return this._Deleted;
            }
            set
            {
                this.OnDeletedChanging(value);
                this._Deleted = value;
                this.OnDeletedChanged();
                this.OnPropertyChanged("Deleted");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private bool _Deleted;
        partial void OnDeletedChanging(bool value);
        partial void OnDeletedChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for RabbitMqRoutingKeyModelSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("RabbitMqRoutingKeyModelSingle")]
    public partial class RabbitMqRoutingKeyModelSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<RabbitMqRoutingKeyModel>
    {
        /// <summary>
        /// Initialize a new RabbitMqRoutingKeyModelSingle object.
        /// </summary>
        public RabbitMqRoutingKeyModelSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new RabbitMqRoutingKeyModelSingle object.
        /// </summary>
        public RabbitMqRoutingKeyModelSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new RabbitMqRoutingKeyModelSingle object.
        /// </summary>
        public RabbitMqRoutingKeyModelSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<RabbitMqRoutingKeyModel> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for RabbitMqRoutingKeyModel in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("RabbitMqRoutingKeyModel")]
    public partial class RabbitMqRoutingKeyModel : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new RabbitMqRoutingKeyModel object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="exchange">Initial value of Exchange.</param>
        /// <param name="queue">Initial value of Queue.</param>
        /// <param name="routingKey">Initial value of RoutingKey.</param>
        /// <param name="actionName">Initial value of ActionName.</param>
        /// <param name="creationDate">Initial value of CreationDate.</param>
        /// <param name="deleted">Initial value of Deleted.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public static RabbitMqRoutingKeyModel CreateRabbitMqRoutingKeyModel(global::System.Guid ID, 
                    string exchange, 
                    string queue, 
                    string routingKey, 
                    string actionName, 
                    global::System.DateTimeOffset creationDate, 
                    bool deleted)
        {
            RabbitMqRoutingKeyModel rabbitMqRoutingKeyModel = new RabbitMqRoutingKeyModel();
            rabbitMqRoutingKeyModel.Id = ID;
            rabbitMqRoutingKeyModel.Exchange = exchange;
            rabbitMqRoutingKeyModel.Queue = queue;
            rabbitMqRoutingKeyModel.RoutingKey = routingKey;
            rabbitMqRoutingKeyModel.ActionName = actionName;
            rabbitMqRoutingKeyModel.CreationDate = creationDate;
            rabbitMqRoutingKeyModel.Deleted = deleted;
            return rabbitMqRoutingKeyModel;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Id")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "Id is required.")]
        public virtual global::System.Guid Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Exchange in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Exchange")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "Exchange is required.")]
        public virtual string Exchange
        {
            get
            {
                return this._Exchange;
            }
            set
            {
                this.OnExchangeChanging(value);
                this._Exchange = value;
                this.OnExchangeChanged();
                this.OnPropertyChanged("Exchange");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Exchange;
        partial void OnExchangeChanging(string value);
        partial void OnExchangeChanged();
        /// <summary>
        /// There are no comments for Property Queue in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Queue")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "Queue is required.")]
        public virtual string Queue
        {
            get
            {
                return this._Queue;
            }
            set
            {
                this.OnQueueChanging(value);
                this._Queue = value;
                this.OnQueueChanged();
                this.OnPropertyChanged("Queue");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _Queue;
        partial void OnQueueChanging(string value);
        partial void OnQueueChanged();
        /// <summary>
        /// There are no comments for Property RoutingKey in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("RoutingKey")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "RoutingKey is required.")]
        public virtual string RoutingKey
        {
            get
            {
                return this._RoutingKey;
            }
            set
            {
                this.OnRoutingKeyChanging(value);
                this._RoutingKey = value;
                this.OnRoutingKeyChanged();
                this.OnPropertyChanged("RoutingKey");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _RoutingKey;
        partial void OnRoutingKeyChanging(string value);
        partial void OnRoutingKeyChanged();
        /// <summary>
        /// There are no comments for Property ActionName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("ActionName")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "ActionName is required.")]
        public virtual string ActionName
        {
            get
            {
                return this._ActionName;
            }
            set
            {
                this.OnActionNameChanging(value);
                this._ActionName = value;
                this.OnActionNameChanged();
                this.OnPropertyChanged("ActionName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private string _ActionName;
        partial void OnActionNameChanging(string value);
        partial void OnActionNameChanged();
        /// <summary>
        /// There are no comments for Property CreationDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("CreationDate")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "CreationDate is required.")]
        public virtual global::System.DateTimeOffset CreationDate
        {
            get
            {
                return this._CreationDate;
            }
            set
            {
                this.OnCreationDateChanging(value);
                this._CreationDate = value;
                this.OnCreationDateChanged();
                this.OnPropertyChanged("CreationDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::System.DateTimeOffset _CreationDate;
        partial void OnCreationDateChanging(global::System.DateTimeOffset value);
        partial void OnCreationDateChanged();
        /// <summary>
        /// There are no comments for Property Deleted in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Deleted")]
        [global::System.ComponentModel.DataAnnotations.RequiredAttribute(ErrorMessage = "Deleted is required.")]
        public virtual bool Deleted
        {
            get
            {
                return this._Deleted;
            }
            set
            {
                this.OnDeletedChanging(value);
                this._Deleted = value;
                this.OnDeletedChanged();
                this.OnPropertyChanged("Deleted");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private bool _Deleted;
        partial void OnDeletedChanging(bool value);
        partial void OnDeletedChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// Class containing all extension methods
    /// </summary>
    public static class ExtensionMethods
    {
        /// <summary>
        /// Get an entity of type global::Ms_configuration.Models.RabbitMqConfigModel as global::Ms_configuration.Models.RabbitMqConfigModelSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="_keys">dictionary with the names and values of keys</param>
        public static global::Ms_configuration.Models.RabbitMqConfigModelSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Ms_configuration.Models.RabbitMqConfigModel> _source, global::System.Collections.Generic.IDictionary<string, object> _keys)
        {
            return new global::Ms_configuration.Models.RabbitMqConfigModelSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Get an entity of type global::Ms_configuration.Models.RabbitMqConfigModel as global::Ms_configuration.Models.RabbitMqConfigModelSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::Ms_configuration.Models.RabbitMqConfigModelSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Ms_configuration.Models.RabbitMqConfigModel> _source,
            global::System.Guid id)
        {
            global::System.Collections.Generic.IDictionary<string, object> _keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::Ms_configuration.Models.RabbitMqConfigModelSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Get an entity of type global::Ms_configuration.Models.RabbitMqRoutingKeyModel as global::Ms_configuration.Models.RabbitMqRoutingKeyModelSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="_keys">dictionary with the names and values of keys</param>
        public static global::Ms_configuration.Models.RabbitMqRoutingKeyModelSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Ms_configuration.Models.RabbitMqRoutingKeyModel> _source, global::System.Collections.Generic.IDictionary<string, object> _keys)
        {
            return new global::Ms_configuration.Models.RabbitMqRoutingKeyModelSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
        /// <summary>
        /// Get an entity of type global::Ms_configuration.Models.RabbitMqRoutingKeyModel as global::Ms_configuration.Models.RabbitMqRoutingKeyModelSingle specified by key from an entity set
        /// </summary>
        /// <param name="_source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::Ms_configuration.Models.RabbitMqRoutingKeyModelSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Ms_configuration.Models.RabbitMqRoutingKeyModel> _source,
            global::System.Guid id)
        {
            global::System.Collections.Generic.IDictionary<string, object> _keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::Ms_configuration.Models.RabbitMqRoutingKeyModelSingle(_source.Context, _source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(_source.Context, _keys)));
        }
    }
}
namespace Default
{
    /// <summary>
    /// There are no comments for Container in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("Container")]
    public partial class Container : global::Microsoft.OData.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new Container object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public Container(global::System.Uri serviceRoot) :
                this(serviceRoot, global::Microsoft.OData.Client.ODataProtocolVersion.V4)
        {
        }

        /// <summary>
        /// Initialize a new Container object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public Container(global::System.Uri serviceRoot, global::Microsoft.OData.Client.ODataProtocolVersion protocolVersion) :
                base(serviceRoot, protocolVersion)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
            this.Format.UseJson();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "ms_configuration.Models", "Ms_configuration.Models");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "Default", "Default");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            global::Microsoft.OData.Client.OriginalNameAttribute originalNameAttribute = (global::Microsoft.OData.Client.OriginalNameAttribute)global::System.Linq.Enumerable.SingleOrDefault(global::Microsoft.OData.Client.Utility.GetCustomAttributes(clientType, typeof(global::Microsoft.OData.Client.OriginalNameAttribute), true));
            if (clientType.Namespace.Equals("Ms_configuration.Models", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("ms_configuration.Models.", originalNameAttribute.OriginalName);
                }
                return string.Concat("ms_configuration.Models.", clientType.Name);
            }
            if (clientType.Namespace.Equals("Default", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("Default.", originalNameAttribute.OriginalName);
                }
                return string.Concat("Default.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for RabbitMqConfigs in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("RabbitMqConfigs")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Ms_configuration.Models.RabbitMqConfigModel> RabbitMqConfigs
        {
            get
            {
                if ((this._RabbitMqConfigs == null))
                {
                    this._RabbitMqConfigs = base.CreateQuery<global::Ms_configuration.Models.RabbitMqConfigModel>("RabbitMqConfigs");
                }
                return this._RabbitMqConfigs;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Ms_configuration.Models.RabbitMqConfigModel> _RabbitMqConfigs;
        /// <summary>
        /// There are no comments for RabbitMqRoutingKeys in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("RabbitMqRoutingKeys")]
        public virtual global::Microsoft.OData.Client.DataServiceQuery<global::Ms_configuration.Models.RabbitMqRoutingKeyModel> RabbitMqRoutingKeys
        {
            get
            {
                if ((this._RabbitMqRoutingKeys == null))
                {
                    this._RabbitMqRoutingKeys = base.CreateQuery<global::Ms_configuration.Models.RabbitMqRoutingKeyModel>("RabbitMqRoutingKeys");
                }
                return this._RabbitMqRoutingKeys;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Ms_configuration.Models.RabbitMqRoutingKeyModel> _RabbitMqRoutingKeys;
        /// <summary>
        /// There are no comments for RabbitMqConfigs in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToRabbitMqConfigs(global::Ms_configuration.Models.RabbitMqConfigModel rabbitMqConfigModel)
        {
            base.AddObject("RabbitMqConfigs", rabbitMqConfigModel);
        }
        /// <summary>
        /// There are no comments for RabbitMqRoutingKeys in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        public virtual void AddToRabbitMqRoutingKeys(global::Ms_configuration.Models.RabbitMqRoutingKeyModel rabbitMqRoutingKeyModel)
        {
            base.AddObject("RabbitMqRoutingKeys", rabbitMqRoutingKeyModel);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private static global::Microsoft.OData.Edm.IEdmModel ParsedModel = LoadModelFromString();

            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private const string filePath = @"ms-configCsdl.xml";

            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            public static global::Microsoft.OData.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private static global::Microsoft.OData.Edm.IEdmModel LoadModelFromString()
            {
                global::System.Xml.XmlReader reader = CreateXmlReader();
                try
                {
                    global::System.Collections.Generic.IEnumerable<global::Microsoft.OData.Edm.Validation.EdmError> errors;
                    global::Microsoft.OData.Edm.IEdmModel edmModel;

                    if (!global::Microsoft.OData.Edm.Csdl.CsdlReader.TryParse(reader, true, out edmModel, out errors))
                    {
                        global::System.Text.StringBuilder errorMessages = new global::System.Text.StringBuilder();
                        foreach (var error in errors)
                        {
                            errorMessages.Append(error.ErrorMessage);
                            errorMessages.Append("; ");
                        }
                        throw new global::System.InvalidOperationException(errorMessages.ToString());
                    }

                    return edmModel;
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }

            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "#VersionNumber#")]
            private static global::System.Xml.XmlReader CreateXmlReader()
            {
                try
                {
                    var assembly = global::System.Reflection.Assembly.GetExecutingAssembly();
                    var resourcePath = global::System.Linq.Enumerable.Single(assembly.GetManifestResourceNames(), str => str.EndsWith(filePath));
                    global::System.IO.Stream stream = assembly.GetManifestResourceStream(resourcePath);
                    return global::System.Xml.XmlReader.Create(new global::System.IO.StreamReader(stream));
                }
                catch(global::System.Xml.XmlException e)
                {
                    throw new global::System.Xml.XmlException("Failed to create an XmlReader from the stream. Check if the resource exists.", e);
                }
            }
        }
    }
}
